"""empty message

Revision ID: 76f4b86d70c1
Revises: 9c2b5d716ef8
Create Date: 2025-07-11 02:58:43.342686

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "76f4b86d70c1"
down_revision: Union[str, Sequence[str], None] = "9c2b5d716ef8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "polls", "options", type_=sa.ARRAY(sa.String()), postgresql_using="options::varchar[]"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "polls",
        "options",
        existing_type=postgresql.ARRAY(sa.String()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
