version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-container
    env_file:
      - /root/fastapi/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    container_name: redis-container
    volumes:
      - redis_data:/var/lib/redis/data
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --bind 0.0.0.0
    restart: unless-stopped
    ports:
      - "6379:6379"
  fastapi:
    image: asdfrewqha/blockchain:latest
    container_name: fastapi-container
    env_file:
      - /root/fastapi/config/.env
    volumes:
      - /root/fastapi/config/.env:/config/.env:ro
    depends_on:
      - postgres
      - redis
    expose:
      - "8000"
    restart: unless-stopped
  rclone:
    image: rclone/rclone:latest
    container_name: rclone
    ports:
      - "127.0.0.1:5572:5572"
    env_file:
      - .env
    environment:
      - RCLONE_ACCESS_KEY=${RCLONE_ACCESS_KEY}
      - RCLONE_SECRET_KEY=${RCLONE_SECRET_KEY}
    volumes:
      - ./rclone:/config/rclone
      - ./data:/data
    command: >
      rcd
      --rc-addr=:5572
      --rc-user=${RCLONE_USER}
      --rc-pass=${RCLONE_PASS}
      --rc-web-gui
      --config=/config/rclone/rclone.conf
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    container_name: nginx-container
    depends_on:
      - fastapi
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/fastapi/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
