version: '3.8'

services:
  ganache:
    image: trufflesuite/ganache:v7.9.1
    container_name: ganache
    ports:
      - "8545:8545"
    command:
      - --wallet.accounts=${REACT_APP_OWNER_PRIVATE_KEY},100000000000000000000
      - --chain.chainId=1337
      - --logging.debug=true

  blockchain:
    build:
      context: ../blockchain
      dockerfile: Dockerfile
    container_name: blockchain
    ports:
      - "2000:2000"
    environment:
      REACT_APP_BLOCKCHAIN_NODE_URL: ${REACT_APP_BLOCKCHAIN_NODE_URL}
      REACT_APP_OWNER_PRIVATE_KEY: ${REACT_APP_OWNER_PRIVATE_KEY}
      REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
      REACT_APP_BACKEND_PORT: ${REACT_APP_BACKEND_PORT}
      REACT_APP_GANACHE_URL: ${REACT_APP_GANACHE_URL}
    depends_on:
      - ganache